version: '3'
services:
  app:
    image: docker.pkg.github.com/0kaoru0/coil_app/coil-app:latest
    environment:
      NODE_ENV: production
    ports:
      - '80:3000'
    links:
      - "mysql"
    restart: always
  mysql:
    image: mysql:5
    command: mysqld --character-set-server=utf8mb4
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./db/db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    restart: always