version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: prodbuild/Dockerfile
    image: registry.nwing.net/coil/coil-app:latest
    environment:
      NODE_ENV: production
    ports:
      - '3005:3000'
    links:
      - "mysql"
    restart: always
  mysql:
    image: mysql:5
    command: mysqld --character-set-server=utf8mb4
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./db/db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    restart: always